### PR TITLE
fix(): bump rjb to newer version

### PR DESCRIPTION
**Pull request by vseguin**
Confirmed it fixes https://github.com/vkononov/fillable-pdf/issues/44.

Seems like there's no other changes required from what I can see.

### CODE REVIEW

**Comment by vkononov** [comment]
@vseguin Thanks for the pull request, but I'm confused - the issue indicated that the gem only works with `rjb@1.6.x` but your pull request updates `rjb` to 1.7, which is confirmed not to be compatible with this gem.

**Comment by vseguin** [comment]
> @vseguin Thanks for the pull request, but I'm confused - the issue indicated that the gem only works with `rjb@1.6.x` but your pull request updates `rjb` to 1.7, which is confirmed not to be compatible with this gem.

Makes sense, I tested and my use case worked but I'm happy to just hardcode to 1.6.9?

**Comment by vseguin** [comment]
> > @vseguin Thanks for the pull request, but I'm confused - the issue indicated that the gem only works with `rjb@1.6.x` but your pull request updates `rjb` to 1.7, which is confirmed not to be compatible with this gem.
> 
> Makes sense, I tested and my use case worked but I'm happy to just hardcode to 1.6.9?

Done that actually.

**Comment by vkononov** [comment]
Sorry for the delay. Instead of hardcoding a specific version, can you change it to:

`spec.add_runtime_dependency 'rjb', '~> 1.6.0'`

This way, people can continue use it with `@rjb@1.6.x`.

Thanks!

**Comment by vseguin** [comment]
> Sorry for the delay. Instead of hardcoding a specific version, can you change it to:
> 
> `spec.add_runtime_dependency 'rjb', '~> 1.6.0'`
> 
> This way, people can continue use it with `@rjb@1.6.x`.
> 
> Thanks!

@vkononov sure, done!

**Comment by vkononov** [comment]
You're very fast! Thanks, Vincent!

**Pull request merged**
